source/hmg/expense_traces/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'expense_traces'

urlpatterns = [
    path('', views.index, name='index'),

    #'''List all Expense Categories'''
    path('expense_categories',views.expense_categories,name='expense_categories'),

    #'''Expenses history'''
    path('expenses',views.expenses,name='expenses'),

    #'''Add New Expense'''
    path('add_expense',views.add_expense,name='add_expense'),

    #'''Add New Category'''
    path('add_category',views.add_expense_category,name='add_expense_category')    

]

source/hmg/hmg/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('',include('expense_traces.urls')),
]

source/hmg/users/urls.py
""" Define URL patterns for users """

from django.urls import path, include

from django.contrib.auth import urls as usersAuthUrls

from . import views

app_name = 'users'

urlpatterns = [
    #include default auth url
    path('', include(usersAuthUrls)),
    path('register', views.register, name='register')
]

source/hmg/expense_traces/models.py
from tkinter import CASCADE
from django.db import models
from djmoney.models.fields import MoneyField
from django.contrib.auth.models import User

# Create your models here.

class Expense_Categories(models.Model):
    expense_type = models.CharField(max_length=25)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self) -> str:
        return f"{self.expense_type}"
        
class Expenses(models.Model):
    '''Adding model for daily expense tracker'''
    ''' A short description of the expense'''
    expense_short = models.CharField(max_length=50)

    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    ''' Expense value'''
    expense_value = MoneyField(max_digits=14, decimal_places=2, default_currency='EUR')
    #expense_value = models.FloatField()
    #expense_currency = models.DecimalField(max_digits=6,decimal_places=2)

    expense_date = models.DateField(auto_now=True)

    #expense_category = models.CharField(max_length=50)
    expense_category = models.ForeignKey(Expense_Categories, on_delete=models.CASCADE)
    def __str__(self) -> str:
        return f"{self.expense_date}: {self.expense_value} - {self.expense_short} - {self.expense_category}" 

source/hmg/users/models.py
from django.db import models

# Create your models here.

source/hmg/expense_traces/forms.py
import django


from django import forms
from .models import Expense_Categories, Expenses

class ExpensesForm(forms.ModelForm):
    class Meta:
        model = Expenses
        fields = ['expense_short', 'expense_value', 'expense_category']
        labels = {
                    'Description':'Enter Short Description',
                    'Value':'Enter value of expenese',
                    'Category':'Enter expense category',
                }

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Expense_Categories
        fields = ['expense_type']
        labels = {
                    'Category':'Add new category here'
                }

source/hmg/expense_traces/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

from .forms import ExpensesForm, CategoryForm


from .models import Expenses, Expense_Categories
# Create your views here.
def index(request):
    '''Home page render'''
    return render(request,'index.html')

@login_required
def expense_categories(request):
    '''List all expense categories here render'''
    expense_categories = Expense_Categories.objects.filter(owner=request.user).order_by('id')
    context = {'categories':expense_categories}
    return render(request,'expense_categories.html',context)

@login_required
def expenses(request):
    '''Render all expenses'''
    expenses = Expenses.objects.filter(owner=request.user).order_by('expense_date')
    context = {'expenses': expenses}
    return render(request, 'expenses.html', context)

@login_required
def add_expense(request):
    '''Add Expenses here'''
    if request.method != 'POST':
        form = ExpensesForm()
    else:
        form = ExpensesForm(data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('expense_traces:expenses')
    context = {'form':form}
    return render(request, 'add_expense.html', context)

@login_required
def add_expense_category(request):
    '''Add categories here'''
    if request.method != 'POST':
        form = CategoryForm()
    else:
        form = CategoryForm(data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('expense_traces:expense_categories')
    context = {'form':form}
    return render(request,'add_categories.html',context)

source/hmg/users/views.py
import imp
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
# Create your views here.

def register(request):
    """Registering a new user"""
    if request.method != 'POST':
        """Provide user creation form"""
        form = UserCreationForm()
    else:
        """Process the registration form"""
        form = UserCreationForm(data=request.POST)

        if (form.is_valid):
            new_user = form.save()
            #Login the user and redirect
            login(request, new_user)
            return redirect('expense_traces:index')

    #Display blank form for user creation
    context = {'form': form}
    return render(request,'registration/registration.html',context)

source/hmg/expense_traces/templates/add_categories.html
{% extends 'base.html' %}

{% block content %}
<h2>Add Expense Category</h2>


<form action = "{% url 'expense_traces:add_expense_category' %}" method ='post'>
    {% csrf_token %}
    {{form.as_p}}
    <button name='submit'>Add Category</button>
</form>

{% endblock content %}

source/hmg/expense_traces/templates/add_expense.html
{% extends 'base.html' %}

{% block content %}
<h2>Add Expense</h2>
<p>
    Here we allow user to add any new expense he made
</p>

<form action = "{% url 'expense_traces:add_expense' %}" method ='post'>
    {% csrf_token %}
    {{form.as_p}}
    <button name='submit'>Add Expense</button>
</form>

{% endblock content %}

source/hmg/expense_traces/templates/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
        <title>Expense Tracker</title>
        
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
    </head>

    <body>
        <nav class="navbar navbar-expand navbar-light bg-light">
            <ul class="nav navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Expenses <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Categories</a>
                </li>
            </ul>
        </nav>
        <h1>Expense Tracker</h1>
        <p>
            <a href="{% url 'expense_traces:expenses' %}"> All Expenses </a> | <a href="{% url 'expense_traces:expense_categories' %}">Categories</a> | 


            {% if user.is_authenticated %}
                Hello, {{user.username}} | 
                <a href = '{% url 'users:logout' %}'>Logout</a>
            {% else %}
                <a href = '{% url 'users:register' %}'>Register</a>
                or 
                <a href = '{% url 'users:login' %}'>Login</a>
            {% endif %}

        </p>
{% block content %}{% endblock content %}

source/hmg/expense_traces/templates/bs4.html
<!doctype html>
<html lang="en">
  <head>
    <title>Expense</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

source/hmg/expense_traces/templates/expense_categories.html
{% extends 'base.html' %}

{% block content %}
<h2>Categories</h2>

<ul>
{% for category in categories %}
    <li>{{category}}</li>
{% endfor %}
</ul>

<a href="{% url 'expense_traces:add_expense_category' %}">Add Categories<a>

{% endblock content %}

source/hmg/expense_traces/templates/expenses.html
{% extends 'base.html' %}

{% block content %}
<h2>Expenses</h2>

<ul>

    {% for expense in expenses %}
    <li>{{expense}}</li>
    {% endfor %}
</ul>
<a href="{% url 'expense_traces:add_expense' %}"> Add new expense <a>
{% endblock content %}

source/hmg/expense_traces/templates/index.html
{% extends 'base.html' %}

{% block content %}

<p>
    Welcome to Expense tracker.  You can track expenses here more optimally
</p>

{% endblock content %}